* :doc:`Introducción a Symfony2 y HTTP </book/http_fundamentals>`
* :doc:`De PHP Plano a Symfony2 </book/from_flat_php_to_symfony2>`
* :doc:`Los Fundamentos de la Creación de Páginas </book/page_creation>`

* :doc:`Controladores </book/controller>`
* :doc:`Enrutamiento </book/routing>`
* :doc:`Plantillas </book/templating>`
* :doc:`Pruebas </book/testing>`

* **Doctrine**:

  * :doc:`DBAL </book/doctrine/dbal/index>` |
  * :doc:`ORM </book/doctrine/orm/index>` |
  * :doc:`Migraciones </book/doctrine/migrations/index>` |
  * :doc:`MongoDB </book/doctrine/mongodb-odm/index>`

* **Validación**:

  * :doc:`Visión General </book/validator/overview>` |
  * :doc:`Validación </book/validator/validation>` |
  * :doc:`/book/validator/constraints`

* **Formularios**:

  * :doc:`Visión General </book/forms/overview>` |
  * :doc:`Plantillas </book/forms/view>` |
  * :doc:`Campos del Formulario </book/forms/fields>`

* **Seguridad**:

  * :doc:`Visión General </book/security/overview>` |
  * :doc:`/book/security/users` |
  * :doc:`/book/security/authentication` |
  * :doc:`/book/security/authorization` |
  * :doc:`ACLs </book/security/acl>` |
  * :doc:`ACLs Avanzados </book/security/acl_advanced>` |
  * :doc:`Referencias de Configuración </book/security/config_reference>`

* :doc:`/book/http_cache`
* :doc:`/book/translation`
* :doc:`Bundles </book/bundles>`
* :doc:`El Contenedor de Servicios </book/service_container>`

* **Funcionamiento Interno**:

  * :doc:`Visión General </book/internals/overview>` |
  * :doc:`Kernel </book/internals/kernel>` |
  * :doc:`Event Dispatcher </book/internals/event_dispatcher>` |
  * :doc:`Profiler </book/internals/profiler>`

* :doc:`API Estable de Symfony2</book/stable_api>`

.. _Twig Templating: http://www.twig-project.org/documentation
